service: pdf-to-excel-converter

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11 # This is now informational, the runtime is defined in the Docker image
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    # Other secrets will be added here later
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"

functions:
  api:
    # Pointing to the directory containing the Dockerfile
    image: ../backend
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+}
          method: any
